version: '2'
services:
  Collector:
    container_name: JaegerCollector
    image: jaegertracing/jaeger-collector:latest
    network_mode: host
    command:
    - --cassandra.keyspace=jaeger_v1_dc1
    - --cassandra.servers=172.16.191.46
    - --collector.zipkin.http-port=9411
    environment:
    - LOG_LEVEL=debug
    ports:
    - 14269
    - 14268:14268
    - 14267
    - 14250:14250
    - 9411:9411
    restart: always
  Agent:
    container_name: JaegerAgent
    image: index.docker.io/jaegertracing/jaeger-agent:latest
    network_mode: host
    environment:
    - REPORTER_GRPC_HOST_PORT=172.16.191.46:14250
    - LOG_LEVEL=debug
    ports:
    - 5775:5775/udp
    - 5778:5778
    - 6831:6831/udp
    - 6832:6832/udp
    restart: always
  Query:
    container_name: JaegerQuery
    image: jaegertracing/jaeger-query:latest
    network_mode: host
    command:
    - --cassandra.keyspace=jaeger_v1_dc1
    - --cassandra.servers=172.16.191.46
    environment:
    - LOG_LEVEL=debug
    ports:
    - 16686:16686
